#! /bin/bash

set -e

function defaultgo {
	go $@\
		code.google.com/p/tasked/sec\
		code.google.com/p/tasked
}

function selfcert {
	key= cert=
	while :
	do
		case $1 in
		-key) shift; key=$1;;
		-cert) shift; cert=$1;;
		"") break;;
		*) shift;;
		esac
	done
	if [ ! "$key" -o ! "$cert" ]; then
		echo 'tsk selfcert -key <key-output-path> -cert <cert-output-path>'
		exit 1
	fi
	mkdir -p $(dirname $key)
	mkdir -p $(dirname $cert)
	openssl req -new -x509 -days 1095 -nodes -out "$cert" -keyout "$key"
}

function testauth {
	go test code.google.com/p/tasked/sec -auth
	go test code.google.com/p/tasked -auth
}

function testintime {
	go test code.google.com/p/tasked/sec -testInTime
	go test code.google.com/p/tasked -testInTime
}

function testfull {
	go test code.google.com/p/tasked/sec -testInTime
	go test code.google.com/p/tasked -testInTime -auth
}

case $1 in
selfcert)
	selfcert $@;;
testauth)
	testauth;;
testintime)
	testintime;;
testfull)
	testfull;;
*)
	defaultgo $@;;
esac

if [ $1 == test ]; then
	chmod -Rf o+r+w+X $testdata
fi
