#! /bin/bash

set -e

function defaultgo {
	go $@\
		code.google.com/p/tasked/auth\
		code.google.com/p/tasked
}

function selfcert {
	key= cert=
	while :
	do
		case $1 in
		-key) shift; key=$1;;
		-cert) shift; cert=$1;;
		"") break;;
		*) shift;;
		esac
	done
	if [ ! "$key" -o ! "$cert" ]; then
		echo 'tsk selfcert -key <key-output-path> -cert <cert-output-path>'
		exit 1
	fi
	mkdir -p $(dirname $key)
	mkdir -p $(dirname $cert)
	openssl req -new -x509 -days 1095 -nodes -out "$cert" -keyout "$key"
}

function test {
	long="" pam="" propsroot="" modpropsroot=""
	while :
	do
		case $1 in
		-long) shift; long="-test.long";;
		-pam) shift; pam="-test.pam";;
		-propsroot) shift; propsroot="-test.propsroot";;
		-modpropsroot) shift; modpropsroot="-test.modpropsroot";;
		"") break;;
		*) shift;;
		esac
	done
	go test code.google.com/p/tasked/auth $long
	go test -i code.google.com/p/tasked
	go test code.google.com/p/tasked $pam
	if [ "$propsroot" != "" ]; then
		go test code.google.com/p/tasked $propsroot
	fi
	if [ "$modpropsroot" != "" ]; then
		go test code.google.com/p/tasked $modpropsroot
	fi
	chmod -Rf o+r+w+X $testdata
}

function createTestUser {
	testuser=testuser
	testpwd=testpwd
	if [ "$1" != "" ]; then testuser=$1; fi
	if [ "$2" != "" ]; then testpwd=$2; fi

	if ! grep '^'$testuser':' /etc/passwd > /dev/null; then
		useradd -p "" $testuser &> /dev/null
	fi
	echo $testuser:$testpwd | chpasswd &> /dev/null
}

case $1 in
selfcert)
	selfcert $@;;
test)
	shift
	test $@;;
testuser)
	shift
	createTestUser $@;;
*)
	defaultgo $@;;
esac
